### ISSUE TITLE
Backward Resolvers for RequestType and Request

### ISSUE THREAD

**Issue by meganniu** [uwblueprint/pregnancy-centre#54]
### Tasks
+ Modify Database Schema
  + Add `RequestGroup` id to `RequestType`
  + Add `RequestType` id to `Request`
+ Write backward GraphQL resolvers
  + `RequestType` resolver should be able to return `RequestType`'s parent `RequestGroup`
  + `Request` resolver should be able to return `Request`'s parent `RequestType`

**Comment by guy-ro** [comment]
Work done was merged into the work for database seeder. Closing this issue!
